name: Build with Docker Build Cloud & Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Build Cloud auth for buildx cloud driver
  DOCKER_BUILD_CLOUD_TOKEN: ${{ secrets.DOCKER_BUILD_CLOUD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx on Docker Build Cloud
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: ${{ vars.DOCKER_BUILD_CLOUD_ENDPOINT }} # <- cloud://hoquet/comfyuibuilder

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/comfyui-depthflow:latest
          provenance: false
          no-cache: true
